Repository devcordde/DevcordBot, pull requests merged in 2020-02, with the labels that each got.

#4 Change Kotlin jvmTarget to 12
  build.gradle.kts
Labels: bug

#5 Feature/inspection profile
  .idea/inspectionProfiles/Project_Default.xml
  build.gradle.kts
Labels: enhancement

#8 Add new event system
  build.gradle.kts
  src/main/kotlin/com/github/seliba/devcordbot/event/_EventSystem.kt
  src/main/kotlin/com/github/seliba/devcordbot/util/DefaultThreadFactory.kt
Labels: documentation, enhancement

#14 Add embed DSL
  build.gradle.kts
  src/main/kotlin/com/github/seliba/devcordbot/constants/Colors.kt
  src/main/kotlin/com/github/seliba/devcordbot/constants/Embeds.kt
  src/main/kotlin/com/github/seliba/devcordbot/constants/Emotes.kt
  src/main/kotlin/com/github/seliba/devcordbot/dsl/_EmbedDSL.kt
  src/main/kotlin/com/github/seliba/devcordbot/event/_EventSystem.kt
Labels: enhancement

#15 Add basic bot
  .env.example
  .gitignore
  .idea/discord.xml
  .idea/vcs.xml
  src/main/kotlin/com/github/seliba/devcordbot/DevcordBot.kt
  src/main/kotlin/com/github/seliba/devcordbot/Launcher.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/GameAnimator.kt
  src/main/kotlin/com/github/seliba/devcordbot/event/_EventSystem.kt
  src/main/kotlin/com/github/seliba/devcordbot/util/DefaultThreadFactory.kt
Labels: documentation, enhancement

#17 Add information embed beeing send when the bot gets mentioned
  build.gradle.kts
  src/main/kotlin/com/github/seliba/devcordbot/Launcher.kt
  src/main/kotlin/com/github/seliba/devcordbot/constants/Colors.kt
  src/main/kotlin/com/github/seliba/devcordbot/constants/Embeds.kt
  src/main/kotlin/com/github/seliba/devcordbot/constants/Emotes.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/DevCordBot.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/GameAnimator.kt
  src/main/kotlin/com/github/seliba/devcordbot/dsl/_EmbedDSL.kt
  src/main/kotlin/com/github/seliba/devcordbot/listeners/SelfMentionListener.kt
  src/main/resources/logback.xml
Labels: enhancement

#19 Add database support
  .env.example
  .gitignore
  build.gradle.kts
  src/main/kotlin/com/github/seliba/devcordbot/Launcher.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/DevCordBot.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/GameAnimator.kt
  src/main/kotlin/com/github/seliba/devcordbot/database/_Entities.kt
  src/main/kotlin/com/github/seliba/devcordbot/database/_Tables.kt
  src/main/kotlin/com/github/seliba/devcordbot/listeners/DatabaseUpdater.kt
Labels: enhancement

#25 Feature/mock command
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/MockCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/DevCordBotImpl.kt
Labels: enhancement

#28 feat: lmgtfy command
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/LmgtfyCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/DevCordBotImpl.kt
Labels: enhancement

#27 Tag command
  .teamcity/target/classes/META-INF/DevcordBot_dsl.kotlin_module
  build.gradle.kts
  src/main/kotlin/com/github/seliba/devcordbot/Launcher.kt
  src/main/kotlin/com/github/seliba/devcordbot/command/AbstractCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/command/AbstractSubCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/command/PermissionHandler.kt
  src/main/kotlin/com/github/seliba/devcordbot/command/context/Arguments.kt
  src/main/kotlin/com/github/seliba/devcordbot/command/context/Context.kt
  src/main/kotlin/com/github/seliba/devcordbot/command/impl/CommandClientImpl.kt
  src/main/kotlin/com/github/seliba/devcordbot/command/impl/RolePermissionHandler.kt
  src/main/kotlin/com/github/seliba/devcordbot/command/perrmission/Permission.kt
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/HelpCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/LmgtfyCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/MockCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/TagCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/constants/Constants.kt
  src/main/kotlin/com/github/seliba/devcordbot/constants/Embeds.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/DevCordBotImpl.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/GameAnimator.kt
  src/main/kotlin/com/github/seliba/devcordbot/database/_Entities.kt
  src/main/kotlin/com/github/seliba/devcordbot/database/_Tables.kt
  src/main/kotlin/com/github/seliba/devcordbot/listeners/SelfMentionListener.kt
  src/main/kotlin/com/github/seliba/devcordbot/util/_UtilExtensions.kt
  src/test/kotlin/CommandTest.kt
Labels: enhancement

#29 hotfix: fix broken command usages
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/LmgtfyCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/MockCommand.kt
Labels: bug

#32 fix: URL encoded arguments
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/LmgtfyCommand.kt
Labels: fixed

#37 feat: add tag raw command
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/HelpCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/TagCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/database/_Entities.kt
  src/main/kotlin/com/github/seliba/devcordbot/menu/Paginator.kt
Labels: enhancement

#39 hotfix: reinitialize bot after ReconnectedEvent gets fired
  src/main/kotlin/com/github/seliba/devcordbot/core/DevCordBotImpl.kt
Labels: enhancement

#40 hotfix: reinitialize bot after ResumedEvent gets fired
  src/main/kotlin/com/github/seliba/devcordbot/core/DevCordBotImpl.kt
Labels: bug

#43 Upgrade dependencies and implement sentry
  .env.example
  .idea/inspectionProfiles/Project_Default.xml
  .teamcity/settings.kts
  build.gradle.kts
  src/main/kotlin/com/github/seliba/devcordbot/Launcher.kt
  src/main/kotlin/com/github/seliba/devcordbot/command/context/Context.kt
  src/main/kotlin/com/github/seliba/devcordbot/command/impl/HastebinErrorHandler.kt
  src/main/kotlin/com/github/seliba/devcordbot/constants/Constants.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/DevCordBot.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/DevCordBotImpl.kt
  src/main/kotlin/com/github/seliba/devcordbot/util/_UtilExtensions.kt
  src/main/resources/logback.xml
Labels: enhancement

#44 Feature/eval
  .env.example
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/EvalCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/MockCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/DevCordBotImpl.kt
  src/main/kotlin/com/github/seliba/devcordbot/util/jdoodle/JDoodle.kt
  src/main/kotlin/com/github/seliba/devcordbot/util/jdoodle/Language.kt
Labels: enhancement

#45 bugfix: mention command test failing
  src/main/kotlin/com/github/seliba/devcordbot/command/impl/CommandClientImpl.kt
  src/test/kotlin/CommandTest.kt
Labels: enhancement

#47 chore: improvements before release
  src/main/kotlin/com/github/seliba/devcordbot/constants/Constants.kt
  src/main/kotlin/com/github/seliba/devcordbot/listeners/SelfMentionListener.kt
Labels: enhancement

#48 hotfix: random messages are being recognized as commands
  src/main/kotlin/com/github/seliba/devcordbot/constants/Constants.kt
Labels: bug

#55 Escape mentions in tags (#53)
  src/main/kotlin/com/github/seliba/devcordbot/command/AbstractCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/TagCommand.kt
  src/test/kotlin/CommandTest.kt
Labels: enhancement

#60 Add CLI
  .idea/jarRepositories.xml
  build.gradle.kts
  src/main/kotlin/com/github/seliba/devcordbot/Launcher.kt
  src/main/kotlin/com/github/seliba/devcordbot/command/impl/CommandClientImpl.kt
  src/main/kotlin/com/github/seliba/devcordbot/command/impl/DebugErrorHandler.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/DevCordBot.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/DevCordBotImpl.kt
Labels: enhancement

#57 Implement bot-owner-only eval command
  .idea/.name
  build.gradle.kts
  src/main/kotlin/com/github/seliba/devcordbot/command/CommandCategory.kt
  src/main/kotlin/com/github/seliba/devcordbot/command/context/Arguments.kt
  src/main/kotlin/com/github/seliba/devcordbot/command/impl/HastebinErrorHandler.kt
  src/main/kotlin/com/github/seliba/devcordbot/command/impl/RolePermissionHandler.kt
  src/main/kotlin/com/github/seliba/devcordbot/command/permission/Permission.kt
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/TagCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/jdoodle/EvalCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/jdoodle/JDoodle.kt
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/jdoodle/Language.kt
  src/main/kotlin/com/github/seliba/devcordbot/commands/owners/EvalCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/constants/Constants.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/DevCordBotImpl.kt
  src/main/kotlin/com/github/seliba/devcordbot/util/HastebinUtil.kt
  src/main/kotlin/com/github/seliba/devcordbot/util/_UtilExtensions.kt
Labels: enhancement

#62 feat: add multi world aliases
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/TagCommand.kt
Labels: enhancement

#65 Add alias for lmgtfy command
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/LmgtfyCommand.kt
Labels: enhancement

#67 feat: Implement starboard
  .env.example
  src/main/kotlin/com/github/seliba/devcordbot/command/impl/CommandClientImpl.kt
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/StarboardCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/TagCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/DevCordBot.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/DevCordBotImpl.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/Starboard.kt
  src/main/kotlin/com/github/seliba/devcordbot/database/_Entities.kt
  src/main/kotlin/com/github/seliba/devcordbot/database/_Tables.kt
  src/main/kotlin/com/github/seliba/devcordbot/dsl/_EmbedDSL.kt
  src/test/kotlin/CommandTest.kt
Labels: enhancement
