Repository devcordde/DevcordBot, pull requests merged in 2020-03, with the labels that each got.

#71 Feature/skid command
  src/main/kotlin/com/github/seliba/devcordbot/command/AbstractCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/command/AbstractSubCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/command/CommandCategory.kt
  src/main/kotlin/com/github/seliba/devcordbot/commands/fun/SourceCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/StarboardCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/DevCordBotImpl.kt
  src/main/kotlin/com/github/seliba/devcordbot/menu/Paginator.kt
Labels: enhancement

#73 Add rank system & rank migrator
  .gitignore
  rankmigrator/build.gradle.kts
  rankmigrator/src/main/java/com/github/seliba/devcordbot/migrator/KotlinHelper.kt
  rankmigrator/src/main/java/com/github/seliba/devcordbot/migrator/Migrator.java
  rankmigrator/src/main/java/com/github/seliba/devcordbot/migrator/TomlData.java
  settings.gradle.kts
  src/main/kotlin/com/github/seliba/devcordbot/listeners/DatabaseUpdater.kt
  src/main/kotlin/com/github/seliba/devcordbot/listeners/RankSystemUpdater.kt
Labels: enhancement

#76 Fix gameanimator
  build.gradle.kts
  rankmigrator/build.gradle.kts
  src/main/kotlin/com/github/seliba/devcordbot/core/DevCordBotImpl.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/GameAnimator.kt
Labels: bug

#77 hotfix: Fix rank system
  src/main/kotlin/com/github/seliba/devcordbot/core/GameAnimator.kt
  src/main/kotlin/com/github/seliba/devcordbot/listeners/RankSystemUpdater.kt
Labels: bug

#79 Hotfix: Update experience calculation
  src/main/kotlin/com/github/seliba/devcordbot/listeners/RankSystemUpdater.kt
Labels: bug, enhancement

#82 Level improvments
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/RankCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/commands/owners/EvalCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/DevCordBotImpl.kt
  src/main/kotlin/com/github/seliba/devcordbot/database/_Entities.kt
  src/main/kotlin/com/github/seliba/devcordbot/database/_Tables.kt
  src/main/kotlin/com/github/seliba/devcordbot/listeners/RankSystemUpdater.kt
  src/main/kotlin/com/github/seliba/devcordbot/util/XPUtil.kt
  src/main/kotlin/com/github/seliba/devcordbot/util/_UtilExtensions.kt
Labels: bug, enhancement

#89 Feature/starboard
  build.gradle.kts
  rankmigrator/build.gradle.kts
  rankmigrator/src/main/java/com/github/seliba/devcordbot/migrator/TomlData.java
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/TagCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/constants/Constants.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/GameAnimator.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/Starboard.kt
  src/main/kotlin/com/github/seliba/devcordbot/database/_Entities.kt
  src/main/kotlin/com/github/seliba/devcordbot/database/_Tables.kt
  src/main/kotlin/com/github/seliba/devcordbot/listeners/RankSystemUpdater.kt
Labels: enhancement
