Repository devcordde/DevcordBot, pull requests merged in 2020-05, with the labels that each got.

#22 Validate upper offset
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/RankCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/CommonPitfallAnalyzer.kt
Labels: bug, enhancement

#28 Fix max offset check
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/RankCommand.kt
Labels: bug, enhancement

#29 Fix max offset (again)
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/RankCommand.kt
Labels: bug, enhancement

#26 Add proper google command
  .env.example
  .idea/jarRepositories.xml
  build.gradle.kts
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/GoogleCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/LmgtfyCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/DevCordBotImpl.kt
  src/main/kotlin/com/github/seliba/devcordbot/menu/Paginator.kt
Labels: enhancement

#32 feat: ignore blacklisted users in RankSystemUpdater
  src/main/kotlin/com/github/seliba/devcordbot/listeners/RankSystemUpdater.kt
Labels: enhancement

#27 Feature/improve autohelp
  .env.example
  src/main/kotlin/com/github/seliba/devcordbot/core/DevCordBotImpl.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/autohelp/AutoHelp.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/autohelp/ContentFetcher.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/autohelp/LanguageGusser.kt
Labels: enhancement

#33 Fix/Google Command
  build.gradle.kts
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/GoogleCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/DevCordBotImpl.kt
Labels: bug

#34 Feature/self redeploy
  .env.example
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/GoogleCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/commands/owners/RedeployCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/core/DevCordBotImpl.kt
Labels: enhancement

#36 Fix/things
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/GoogleCommand.kt
  src/main/kotlin/com/github/seliba/devcordbot/listeners/RankSystemUpdater.kt
Labels: bug, enhancement

#39 hotfix/remove debug log
  src/main/kotlin/com/github/seliba/devcordbot/core/autohelp/AutoHelp.kt
Labels: enhancement
