Repository devcordde/DevcordBot, pull requests merged in 2020-06, with the labels that each got.

#40 Add haste host to the .env file
  .env.example
  src/main/kotlin/com/github/seliba/devcordbot/Launcher.kt
  src/main/kotlin/com/github/seliba/devcordbot/constants/Constants.kt
Labels: enhancement

#49 fix: StringIndexOutOfBoundsException
  src/main/kotlin/com/github/seliba/devcordbot/commands/general/TagCommand.kt
Labels: bug

#55 Feature/cleanup command
  src/main/kotlin/com/github/devcordde/devcordbot/commands/owners/CleanupCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/core/DevCordBotImpl.kt
  src/main/resources/logback.xml
Labels: enhancement

#59 Fix the rank top offset
  src/main/kotlin/com/github/devcordde/devcordbot/commands/general/RankCommand.kt
Labels: bug, enhancement

#60 Feature/dev environment
  README.md
  docker-compose.develop.yml
  docker-compose.yml
Labels: documentation

#62 fix: respond
  src/main/kotlin/com/github/devcordde/devcordbot/commands/owners/CleanupCommand.kt
Labels: bug, enhancement

#67 Fix rank top offset
  src/main/kotlin/com/github/devcordde/devcordbot/commands/general/RankCommand.kt
Labels: bug, enhancement

#64 Fix the docker compose development file
  docker-compose.develop.yml
Labels: bug

#63 Update dev environment setup in the README
  README.md
Labels: bug, enhancement

#69 fix/tests
  src/main/kotlin/com/github/devcordde/devcordbot/command/impl/CommandClientImpl.kt
  src/main/kotlin/com/github/devcordde/devcordbot/command/impl/RolePermissionHandler.kt
  src/main/kotlin/com/github/devcordde/devcordbot/commands/general/RankCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/commands/moderation/BlacklistCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/commands/owners/CleanupCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/core/autohelp/AutoHelp.kt
  src/main/kotlin/com/github/devcordde/devcordbot/database/_Entities.kt
  src/main/kotlin/com/github/devcordde/devcordbot/event/DevCordMessageReceivedEvents.kt
  src/main/kotlin/com/github/devcordde/devcordbot/listeners/RankSystemUpdater.kt
Labels: bug

#73 feature/improve auto help - github contributors
  .idea/compiler.xml
  src/main/kotlin/com/github/devcordde/devcordbot/command/impl/CommandClientImpl.kt
  src/main/kotlin/com/github/devcordde/devcordbot/commands/general/InfoCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/commands/general/RankCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/core/DevCordBot.kt
  src/main/kotlin/com/github/devcordde/devcordbot/core/DevCordBotImpl.kt
  src/main/kotlin/com/github/devcordde/devcordbot/core/autohelp/AutoHelp.kt
  src/main/kotlin/com/github/devcordde/devcordbot/core/autohelp/LanguageGusser.kt
  src/main/kotlin/com/github/devcordde/devcordbot/database/_Entities.kt
  src/main/kotlin/com/github/devcordde/devcordbot/listeners/SelfMentionListener.kt
  src/main/kotlin/com/github/devcordde/devcordbot/util/GithubUtil.kt
  src/main/kotlin/com/github/devcordde/devcordbot/util/_UtilExtensions.kt
Labels: enhancement

#75 Fix #74
  .idea/compiler.xml
  .idea/discord.xml
  build.gradle.kts
  src/main/kotlin/com/github/devcordde/devcordbot/core/autohelp/LanguageGusser.kt
  src/main/kotlin/com/github/devcordde/devcordbot/menu/Paginator.kt
Labels: bug

#76 bugfix: actually handle level limit correctly
  build.gradle.kts
  src/main/kotlin/com/github/devcordde/devcordbot/core/autohelp/AutoHelp.kt
Labels: bug

#85 fix: put search name in code tags
  src/main/kotlin/com/github/devcordde/devcordbot/commands/general/TagCommand.kt
Labels: bug

#86 Javadoc
  build.gradle.kts
  src/main/kotlin/com/github/devcordde/devcordbot/commands/general/AbstractJavadocCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/commands/general/DocumentedVersion.kt
  src/main/kotlin/com/github/devcordde/devcordbot/commands/general/JavadocCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/commands/general/_JavadocCommands.kt
  src/main/kotlin/com/github/devcordde/devcordbot/core/DevCordBotImpl.kt
Labels: enhancement
