Repository devcordde/DevcordBot, pull requests merged in 2021-05, with the labels that each got.

#169 Update develop
  .github/workflows/gradle.yml
  .idea/codeStyles/Project.xml
  .idea/compiler.xml
  Dockerfile
  build.gradle.kts
  src/main/kotlin/com/github/devcordde/devcordbot/Launcher.kt
  src/main/kotlin/com/github/devcordde/devcordbot/commands/general/RankCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/core/DevCordBotImpl.kt
  src/main/kotlin/com/github/devcordde/devcordbot/core/autohelp/ContentFetcher.kt
  src/main/kotlin/com/github/devcordde/devcordbot/database/_Tables.kt
Labels: enhancement

#172 chore: update autohelp to 1.1.2
  build.gradle.kts
Labels: bug, enhancement

#171 fix: try to fix sentry
  src/main/kotlin/com/github/devcordde/devcordbot/Launcher.kt
  src/main/kotlin/com/github/devcordde/devcordbot/core/DevCordBotImpl.kt
Labels: bug

#173 chore: Bump autohelp to 1.2.0
  build.gradle.kts
  src/main/kotlin/com/github/devcordde/devcordbot/core/DevCordBotImpl.kt
Labels: bug

#170 Updated mentioned command to slash command
  src/main/kotlin/com/github/devcordde/devcordbot/commands/general/HelpCommand.kt
Labels: bug

#178 Bugfixes
  build.gradle.kts
  src/main/java/net/dv8tion/jda/api/utils/MarkdownSanitizer.java
  src/main/kotlin/com/github/devcordde/devcordbot/command/AbstractSubCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/command/context/Arguments.kt
  src/main/kotlin/com/github/devcordde/devcordbot/commands/general/jdoodle/JDoodle.kt
Labels: bug

#180 fix: haste post messages only containing the keys
  src/main/kotlin/com/github/devcordde/devcordbot/command/impl/HastebinErrorHandler.kt
  src/main/kotlin/com/github/devcordde/devcordbot/commands/general/TagCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/commands/general/jdoodle/EvalCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/commands/owners/EvalCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/util/HastebinUtil.kt
Labels: bug

#181 fix: remove unwanted markdown sanitization, add tag validation again
  src/main/kotlin/com/github/devcordde/devcordbot/commands/general/TagCommand.kt
Labels: bug

#187 More bugfixes
  .github/workflows/gradle.yml
  src/main/kotlin/com/github/devcordde/devcordbot/Launcher.kt
  src/main/kotlin/com/github/devcordde/devcordbot/command/impl/CommandClientImpl.kt
  src/main/kotlin/com/github/devcordde/devcordbot/command/root/AbstractRootCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/command/root/AbstractSingleCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/command/root/RegisterableCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/commands/fun/SourceCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/commands/general/GoogleCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/commands/general/HelpCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/commands/general/InfoCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/commands/general/RankCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/commands/general/RanksCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/commands/general/TagCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/commands/general/jdoodle/EvalCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/commands/general/jdoodle/JDoodle.kt
  src/main/kotlin/com/github/devcordde/devcordbot/commands/moderation/BlacklistCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/commands/owners/CleanupCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/commands/owners/EvalCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/commands/owners/RedeployCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/constants/Embeds.kt
Labels: CI, bug, enhancement

#188 fix: jdoodle timeout feature
  src/main/kotlin/com/github/devcordde/devcordbot/core/DevCordBotImpl.kt
Labels: bug

#189 hotfix: slash command permissions not working
  src/main/kotlin/com/github/devcordde/devcordbot/command/impl/RolePermissionHandler.kt
Labels: bug

#190 fix: bot owner permissions, blacklist command for moderators
  src/main/kotlin/com/github/devcordde/devcordbot/commands/moderation/BlacklistCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/core/DevCordBotImpl.kt
Labels: bug

#198 Fix rank system
  .env.example
  src/main/kotlin/com/github/devcordde/devcordbot/config/Config.kt
  src/main/kotlin/com/github/devcordde/devcordbot/config/ConfigSpec.kt
  src/main/kotlin/com/github/devcordde/devcordbot/listeners/RankSystemUpdater.kt
Labels: bug

#196 fix: correct max length of normal messages
  src/main/kotlin/com/github/devcordde/devcordbot/constants/Constants.kt
  src/main/kotlin/com/github/devcordde/devcordbot/constants/DiscordConstants.kt
  src/main/kotlin/com/github/devcordde/devcordbot/database/_Tables.kt
Labels: bug

#200 fix: owner eval command
  src/main/kotlin/com/github/devcordde/devcordbot/commands/owners/EvalCommand.kt
  src/main/kotlin/com/github/devcordde/devcordbot/listeners/DevmarktRequestUpdater.kt
Labels: bug, enhancement

#201 chore: update kord
  build.gradle.kts
Labels: bug
