Repository devcordde/DevcordBot, pull requests merged in 2021-04, with the labels that each got.

#160 chore: update Gradle to 7.0
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#161 fix: update docker repository
  .github/workflows/gradle.yml
  docker-compose.yml
Labels: CI, bug

#159 fix: connection leak in attachment fetcher
  src/main/kotlin/com/github/devcordde/devcordbot/Launcher.kt
  src/main/kotlin/com/github/devcordde/devcordbot/core/autohelp/ContentFetcher.kt
Labels: bug

#162 fix: add tag length validation
  src/main/kotlin/com/github/devcordde/devcordbot/commands/general/TagCommand.kt
Labels: bug

#164 Optimize build process
  .github/workflows/gradle.yml
  .idea/codeStyles/Project.xml
  Dockerfile
  build.gradle.kts
Labels: CI, enhancement

#167 Fix CI trigger
  .github/workflows/gradle.yml
Labels: CI, bug
